// const ShopActionTypes = {
//     UPDATE_COLLECTION: 'UPDATE_COLLECTION'
// }

const ShopActionTypes = {
    FETCH_COLLECTIONS_START : 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS : 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAIL : 'FETCH_COLLECTIONS_FAIL'
}

export default ShopActionTypes